# fly.toml file generated for vault-unsealer on 2023-02-05T13:55:18+01:00

app = "vault-unsealer"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
source="vault_unsealer"
destination="/vault"

[env]
VAULT_API_ADDR="https://vault-unsealer.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8200
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  # [[services.http_checks]]
  #   interval = 10000
  #   grace_period = "5s"
  #   method = "get"
  #   path = "/v1/sys/health"
  #   protocol = "http"
  #   restart_limit = 0
  #   timeout = 2000
  #   tls_skip_verify = false
