name: Deploy to Fly
on:
  pull_request:
    paths:
      - 'vault-unsealer/**'
      - '!vault-unsealer/docs/**'
jobs:
  check-dockerfile:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: vault-unsealer/Dockerfile

# name: Leaked Secrets Scan
# on: [pull_request]
# jobs:
  leaked-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  deploy:
    name: Deploy vault-unsealer app
    needs: ["check-dockerfile"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --region ams
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./vault-unsealer
