name: Deploy to Fly
on:
  pull_request:
    paths:
      - 'vault-unsealer/**'
      - '!vault-unsealer/docs/**'
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile

      # - run: flyctl deploy --remote-only --region ams
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
